name: Deployment
on:
  push:
    branches:
      - main
      - dev
jobs:
  test:
    env:
       MONGODB_CLUSTER_ADDRESS: mongodb.s25olrz.mongodb.net
       MONGODB_USERNAME: muheyuddin
       MONGODB_PASSWORD: euIXyCHN1RoRT0ko
       PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: | 
              echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME}}"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MongoDB Username: ${{env.MONGODB_USERNAME}}"
          echo "MongoDB DB Name: ${{github.actor}}"
